### ISSUE TITLE
not able to run

### ISSUE THREAD

**Issue by finalight** [SignalGarden/tango_unity_mit#1]
is there a scene for this? because I want to know what's the setting for the tango manager and tango camera

**Comment by dylan-hart** [comment]
Thanks for your feedback!

There's no scene included in the workshop package, but the included instructions (.docx or .pdf) have steps for setting up a scene from scratch. #6 of part one indicates the settings for tango manager (it's tweaked a bit later in part two as well) and #7 of part one indicates the settings for tango delta camera (just disable the character controller script). The tango delta camera is replaced in part two with tango AR camera, and there's significant changes to that described in the instructions (which may or may not be correct for Tango releases beyond Wasat).

I just walked through the instructions for 1-1 myself with the Wasat release and can confirm the mesh generation isn't working. Have you tried importing the latest Tango release instead?

I have an obligation this morning, but when I'm free later today I'll do my best to update/debug this issue.

**Comment by dylan-hart** [comment]
Updated the instructions and packages for the latest Tango release (Gankino). If this doesn't solve the issue you're experiencing, give us some more detail (does it compile/build? does it run in the editor? what device are you using? etc.) and we'll do our best to help you get it working.

**Comment by finalight** [comment]
I followed your newly updated instructions and this is the final result:

![screenshot_20170425-121612](https://cloud.githubusercontent.com/assets/4475526/25368889/8e77f026-29b2-11e7-8a9f-6790b7dce4e7.png)
![screenshot_20170425-121616](https://cloud.githubusercontent.com/assets/4475526/25368887/8e727506-29b2-11e7-9391-94c6307f1009.png)
![screenshot_20170425-122606](https://cloud.githubusercontent.com/assets/4475526/25368888/8e72ffee-29b2-11e7-9a35-a8eabc0574ba.png)

There's no collision happening when i throw the sphere/cube on the floor. Did I miss out important things in the documentation? I was actually expecting something similar to the video in the snapshot folder

**Comment by dylan-hart** [comment]
Interesting! Is it possible for you to attach a zip of your unity project here? I'll look through it and see what I can find, if so. Otherwise, here's a few guesses:

(for the collision issue)
does the Tango Dynamic Mesh object have a Mesh Collider component?

(for the color, if the RenderTexture isn't applied yet)
does Tango Manager have "generate color" checked?

(for the color, if the RenderTexture /is/ applied)
is the material applied to the Tango Dynamic Mesh using the AR projection shader?
does that material have the RenderTexture set as its texture?

sorry for the basic questions. I'll need to know more or see the project to ask better ones. One last question: am I correct in thinking the floor/wall mesh is all a flat color and that color is changing as you move your Tango device around? this might possibly indicate something is going wrong in the shader's projection of the render texture.

**Comment by finalight** [comment]
i'm quite confused at this part, this is at 2.2 part 8

<img width="760" alt="screen shot 2017-04-25 at 9 46 58 pm" src="https://cloud.githubusercontent.com/assets/4475526/25388576/cb522b9e-2a00-11e7-997a-b6963ee2623a.png">

do I actually have to replace the original code with this?
also, is it possible for me to contact you directly via telegram/gitter/slack? that way we can have a faster conversation.

as for the above issue, let me try to redo one from scratch and see if i am able to reproduce the problem

thanks a lot

**Comment by dylan-hart** [comment]
ah, OK! yes, that's the entire shader, so the AR projection shader should look exactly like that - the simplest approach might be to delete all the default code unity creates in the shader first. I'll make that clearer in the instructions in the future.

there is a tango-specific slack, tangodevelopers.slack.com, that we could use if you'd like. i believe it's open for anyone to join. my username is dylan.hart.

you're welcome!

**Comment by finalight** [comment]
it's only available for people with signalgarden email

possible to contact the administrator to let me have access to it if possible?

**Comment by dylan-hart** [comment]
ah OK. send an email to chuck@knowledge.wtf

**Comment by finalight** [comment]
thanks for the help!
